name = "Modded Faction SMP"
author = "Eth"
version = "1.0.0"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "a75c393145ab8c4a458d9b19fc446a29d8d032534dcb8a9c0b8ebbd471629fdc"

[versions]
fabric = "0.14.9"
minecraft = "1.19"
