name = "Modded Faction SMP"
author = "Eth"
version = "1.0.0"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "30581a985c33e19c5a8365b4bd70e4d0a906863fea220e5d49dda71d76e40f99"

[versions]
fabric = "0.14.9"
minecraft = "1.19"
