name = "Modded Faction SMP"
author = "Eth"
version = "1.0.0"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "444a08657b1922e101ed3ba1f68cc6e9836361752bff77d4c4d160d11d5af44e"

[versions]
fabric = "0.14.9"
minecraft = "1.19"
